# Please set 'QIITA_TOKEN' secret to your repository
name: Publish Qiita Articles

on:
  push:
    branches:
      - main
      - master
    paths:
      - "qiita/**"
      - ".github/workflows/qiita-publish.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Qiita CLI
        run: npm install -g @qiita/qiita-cli@latest
      - name: Publish Qiita Articles
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
        run: qiita publish --all --root ./qiita
